### ISSUE TITLE
bug SI Units

### ISSUE THREAD

**Issue by mdengusiak** [PayettePeople/Thermal-Comfort-Tool#18]
Hi,

SI Units does not seems to be working...

![image](https://user-images.githubusercontent.com/14005893/27482453-6daa39cc-5819-11e7-957d-2c5ce2079a86.png)

**Comment by chriswmackey** [comment]
@mdengusiak ,

Thanks for posting the issue.  I can't seem to re-create it on my end, though.  The only way that I get a screenshot like the one that you have is if I first paste the URL into my browser (it shows up in SI) and then I manually change it over to IP.

Are you saying that you expect the URL to automatically update as you change parameters?  We did not build this into the tool as it would result in very long URLs most of the time.  Accordingly, if you want to send someone an updated URL, you should hit the "Copy URL" button (this will always be generated based on the most recent parameters).

Maybe I should cut out all of the extra stuff in the URL whenever someone pastes in a long URL like this.  I'll try to implement this soon to avoid future confusion.

-Chris

**Comment by chriswmackey** [comment]
I was finally able to recreate this one.  I fixed it on the github here:
https://github.com/PayettePeople/Thermal-Comfort-Tool/commit/f8910b71786cfaa1e6b951b1df61785f9709ae28

...and I am fixing it on the Payette site now.
